x-shared-environment: &common-env
  environment:
    POSTGRES_HOST: db
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD_FILE: /run/secrets/db_password
  secrets:
    - db_password

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api:ro
    <<: *common-env
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: postgres:16.2-alpine3.19
    <<: *common-env
    ports:
      - "5432:5432"
    volumes:
      - ./.pgdata:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    restart: always

secrets:
  db_password:
    file: ./db_password.txt
